services:
  # Service Rabbit MQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - private

  # Main server
  server:
    build:
      args:
        - NODE_ENV=PRODUCTION
        - SERVER_TYPE=MAIN
      context: back-end
      target: production
    command: npm run start
    env_file: ./back-end/.env

    ports:
      - 3000:3000
    volumes:
      - ./back-end:/base:ro
    networks:
      - public
      - private
    depends_on:
      - rabbitmq

  # Notification service
  notification-service:
    command: npm run start:notify
    ports:
      - 3555:3555
    volumes:
      - ./back-end:/base:ro
    networks:
      - public
      - private
    depends_on:
      - server

  # Video service
  video-service:
    command: npm run start:video
    volumes:
      - ./back-end:/base:ro
    networks:
      - private
    depends_on:
      - server
  # db:
  #   # We use a mariadb image which supports both amd64 & arm64 architecture
  #   image: mariadb:10.6.4-focal
  #   # If you really want to use MySQL, uncomment the following line
  #   #image: mysql:8.0.27
  #   command: "--default-authentication-plugin=mysql_native_password"
  #   restart: always
  #   secrets:
  #     - db-password
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - private
  #   environment:
  #     - MYSQL_DATABASE=example
  #     - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  frontend:
    build:
      context: frontend
      target: production
    ports:
      - 4000:4000
    volumes:
      - ./front-end:/base/src
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
  private:
volumes:
  back-end:
    external: true
  front-end:
