services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - private

  #Main server
  server:
    build:
      context: backend
      target: operation
    command: npm run db:auto-prod && npm run start
    env_file: ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - ./backend:/base:ro
    networks:
      - public
      - private
    depends_on:
      - rabbitmq

  # Notification service
  notification-service:
    image: amd64/node
    command: npm run start:notify
    ports:
      - 3555:3555
    working_dir: /base
    volumes:
      - ./backend:/base:ro
    networks:
      - public
      - private
    depends_on:
      - server

  # Video service
  video-service:
    image: amd64/node
    command: npm run start:video
    working_dir: /base
    volumes:
      - ./backend:/base:ro
    networks:
      - private
    depends_on:
      - server

  # Front end
  frontend:
    build:
      context: frontend
      target: build
    ports:
      - 4001:4001
    command: npx serve dist
    volumes:
      - ./frontend:/base/src
    networks:
      - public
    depends_on:
      - server
  cypress:
    image: "cypress/included:7.5.0"
    depends_on:
      - frontend
    entrypoint: cypress open --project /e2e
    environment:
      - CYPRESS_baseUrl=http://localhost:4001
      - CYPRESS_VIDEO=false
    volumes:
      - ./frontend/.:/e2e

networks:
  public:
  private:
    driver: bridge
volumes:
  backend:
    external: true
  frontend:
    external: true
  db:
